--  REST API Validation
--  API to validate
--
--  The version of the OpenAPI document: 1.0.0
--  Contact: Stephane.Carrez@gmail.com
--
--  NOTE: This package is auto generated by OpenAPI-Generator 6.1.0-2022-07-31.
--  https://openapi-generator.tech
--  Do not edit the class manually.

with Swagger.Streams;
with Ada.Containers.Vectors;
package TestAPI.Models is
   pragma Style_Checks ("-bmrIu");

   type StringsMap_Type is record
      Key : Swagger.Nullable_UString;
   end record;

   package StringsMap_Type_Vectors is new Ada.Containers.Vectors
     (Index_Type => Positive, Element_Type => TestAPI.Models.StringsMap_Type);

   procedure Serialize
     (Into  : in out Swagger.Streams.Output_Stream'Class;
      Name  : in     String;
      Value : in     TestAPI.Models.StringsMap_Type);

   procedure Serialize
     (Into  : in out Swagger.Streams.Output_Stream'Class;
      Name  : in     String;
      Value : in     StringsMap_Type_Vectors.Vector);

   procedure Deserialize
     (From  : in     Swagger.Value_Type;
      Name  : in     String;
      Value :    out TestAPI.Models.StringsMap_Type);

   procedure Deserialize
     (From  : in     Swagger.Value_Type;
      Name  : in     String;
      Value : in out StringsMap_Type_Vectors.Vector);

   type OrchStoreRequest_Type is record
      Requested_Qo_S : TestAPI.Models.StringsMap_Type;
      Commands       : TestAPI.Models.StringsMap_Type;
   end record;

   package OrchStoreRequest_Type_Vectors is new Ada.Containers.Vectors
     (Index_Type   => Positive,
      Element_Type => TestAPI.Models.OrchStoreRequest_Type);

   procedure Serialize
     (Into  : in out Swagger.Streams.Output_Stream'Class;
      Name  : in     String;
      Value : in     TestAPI.Models.OrchStoreRequest_Type);

   procedure Serialize
     (Into  : in out Swagger.Streams.Output_Stream'Class;
      Name  : in     String;
      Value : in     OrchStoreRequest_Type_Vectors.Vector);

   procedure Deserialize
     (From  : in     Swagger.Value_Type;
      Name  : in     String;
      Value :    out TestAPI.Models.OrchStoreRequest_Type);

   procedure Deserialize
     (From  : in     Swagger.Value_Type;
      Name  : in     String;
      Value : in out OrchStoreRequest_Type_Vectors.Vector);

   --  ------------------------------
   --  Information about a ticket
   --  ------------------------------

   type Ticket_Type is record
      Id          : Swagger.Long;
      Title       : Swagger.UString;
      Description : Swagger.UString;
      Owner       : Swagger.Nullable_UString;
      Create_Date : Swagger.Datetime;
      End_Date    : Swagger.Nullable_Date;
      Update_Date : Swagger.Nullable_Date;
      Status      : Swagger.UString;
   end record;

   package Ticket_Type_Vectors is new Ada.Containers.Vectors
     (Index_Type => Positive, Element_Type => TestAPI.Models.Ticket_Type);

   procedure Serialize
     (Into  : in out Swagger.Streams.Output_Stream'Class;
      Name  : in     String;
      Value : in     TestAPI.Models.Ticket_Type);

   procedure Serialize
     (Into  : in out Swagger.Streams.Output_Stream'Class;
      Name  : in     String;
      Value : in     Ticket_Type_Vectors.Vector);

   procedure Deserialize
     (From  : in     Swagger.Value_Type;
      Name  : in     String;
      Value :    out TestAPI.Models.Ticket_Type);

   procedure Deserialize
     (From  : in     Swagger.Value_Type;
      Name  : in     String;
      Value : in out Ticket_Type_Vectors.Vector);

   type Options_Type is record
      A : Swagger.UString_Vectors.Vector;
   end record;

   package Options_Type_Vectors is new Ada.Containers.Vectors
     (Index_Type => Positive, Element_Type => TestAPI.Models.Options_Type);

   procedure Serialize
     (Into  : in out Swagger.Streams.Output_Stream'Class;
      Name  : in     String;
      Value : in     TestAPI.Models.Options_Type);

   procedure Serialize
     (Into  : in out Swagger.Streams.Output_Stream'Class;
      Name  : in     String;
      Value : in     Options_Type_Vectors.Vector);

   procedure Deserialize
     (From  : in     Swagger.Value_Type;
      Name  : in     String;
      Value :    out TestAPI.Models.Options_Type);

   procedure Deserialize
     (From  : in     Swagger.Value_Type;
      Name  : in     String;
      Value : in out Options_Type_Vectors.Vector);

end TestAPI.Models;
