--  REST API Validation
--  API to validate
--
--  The version of the OpenAPI document: 1.0.0
--  Contact: Stephane.Carrez@gmail.com
--
--  NOTE: This package is auto generated by OpenAPI-Generator 7.11.0-2024-11-24.
--  https://openapi-generator.tech
--  Do not edit the class manually.

with Enums.Models;
with OpenAPI.Clients;
package Enums.Clients is
   pragma Style_Checks ("-bmrIu");

   type Client_Type is new OpenAPI.Clients.Client_Type with null record;

   --  Get some stat from external struct
   procedure Do_Get_Enums
     (Client : in out Client_Type;
      Status : in     Enums.Models.Status_Type;
      Result :    out Enums.Models.Stat_Type_Vectors.Vector);

   --  Get an object
   --  Get an object
   procedure Do_Get_Object
     (Client : in out Client_Type;
      Status : in     Enums.Models.Status_Type;
      Owner  : in     OpenAPI.Nullable_UString;
      Result :    out OpenAPI.Object);

end Enums.Clients;
