--  REST API types validation
--  Types to validate
--
--  The version of the OpenAPI document: 1.0.0
--
--
--  NOTE: This package is auto generated by OpenAPI-Generator 7.11.0-2024-11-24.
--  https://openapi-generator.tech
--  Do not edit the class manually.

pragma Warnings (Off, "*is not referenced");
with OpenAPI.Streams;
package body Types.Clients is
   pragma Style_Checks ("-bmrIu");

   Media_List_1 : constant OpenAPI.Mime_List := (1 => OpenAPI.Mime_Json);

   --
   procedure Add_Rack
     (Client    : in out Client_Type;
      Rack_Info : in     Types.Models.RackInfo_Type;
      Result    :    out Types.Models.RackInfo_Type)
   is
      URI   : OpenAPI.Clients.URI_Type;
      Req   : OpenAPI.Clients.Request_Type;
      Reply : OpenAPI.Value_Type;
   begin
      Client.Set_Accept (Media_List_1);
      Client.Initialize (Req, Media_List_1);
      Types.Models.Serialize (Req.Stream, "", Rack_Info);

      URI.Set_Path ("/racks");
      Client.Call (OpenAPI.Clients.POST, URI, Req, Reply);
      Types.Models.Deserialize (Reply, "", Result);
   end Add_Rack;

   --
   procedure Get_Rack
     (Client : in out Client_Type;
      Name   : in     OpenAPI.Long;
      Result :    out Types.Models.RackInfo_Type)
   is
      URI   : OpenAPI.Clients.URI_Type;
      Reply : OpenAPI.Value_Type;
   begin
      Client.Set_Accept (Media_List_1);

      URI.Set_Path ("/racks/{name}");
      URI.Set_Path_Param ("name", OpenAPI.To_String (Name));
      Client.Call (OpenAPI.Clients.GET, URI, Reply);
      Types.Models.Deserialize (Reply, "", Result);
   end Get_Rack;

   --
   procedure Update_Rack
     (Client    : in out Client_Type;
      Name      : in     OpenAPI.Long;
      Rack_Info : in     Types.Models.RackInfo_Type;
      Result    :    out Types.Models.RackInfo_Type)
   is
      URI   : OpenAPI.Clients.URI_Type;
      Req   : OpenAPI.Clients.Request_Type;
      Reply : OpenAPI.Value_Type;
   begin
      Client.Set_Accept (Media_List_1);
      Client.Initialize (Req, Media_List_1);
      Types.Models.Serialize (Req.Stream, "", Rack_Info);

      URI.Set_Path ("/racks/{name}");
      URI.Set_Path_Param ("name", OpenAPI.To_String (Name));
      Client.Call (OpenAPI.Clients.PUT, URI, Req, Reply);
      Types.Models.Deserialize (Reply, "", Result);
   end Update_Rack;
end Types.Clients;
