--  REST API Validation
--  API to validate
--
--  The version of the OpenAPI document: 1.0.0
--  Contact: Stephane.Carrez@gmail.com
--
--  NOTE: This package is auto generated by OpenAPI-Generator 7.11.0-2024-11-24.
--  https://openapi-generator.tech
--  Do not edit the class manually.

pragma Warnings (Off, "*is not referenced");
with OpenAPI.Streams;
with OpenAPI.Servers.Operation;
package body TestAPI.Skeletons is
   pragma Style_Checks ("-bmrIu");
   pragma Warnings (Off, "*use clause for package*");

   use OpenAPI.Streams;

   Media_List_1 : aliased constant OpenAPI.Mime_List :=
     (1 => OpenAPI.Mime_Json);

   Media_List_2 : aliased constant OpenAPI.Mime_List :=
     (1 => OpenAPI.Mime_Text);

   Media_List_3 : aliased constant OpenAPI.Mime_List :=
     (1 => OpenAPI.Mime_Form);

   package body Skeleton is

      package API_Orch_Store is new OpenAPI.Servers.Operation
        (Handler => Orch_Store,
         Method  => OpenAPI.Servers.POST,
         URI     => URI_Prefix & "/orchestration",
         Mimes   => null);

      --
      procedure Orch_Store
        (Req     : in out OpenAPI.Servers.Request'Class;
         Reply   : in out OpenAPI.Servers.Response'Class;
         Stream  : in out OpenAPI.Servers.Output_Stream'Class;
         Context : in out OpenAPI.Servers.Context_Type)
      is
         Input              : OpenAPI.Value_Type;
         Impl               : Implementation_Type;
         Orch_Store_Request : OrchStoreRequest_Type;
      begin

         OpenAPI.Servers.Read (Req, Media_List_1, Input);
         if OpenAPI.Is_Null (Input) then
            Context.Set_Error (415, "Invalid content");
            return;
         end if;

         TestAPI.Models.Deserialize (Input, "", Orch_Store_Request);
         Impl.Orch_Store (Orch_Store_Request, Context);

      end Orch_Store;

      package API_Test_Int is new OpenAPI.Servers.Operation
        (Handler => Test_Int,
         Method  => OpenAPI.Servers.GET,
         URI     => URI_Prefix & "/testInt",
         Mimes   => Media_List_1'Access);

      --
      procedure Test_Int
        (Req     : in out OpenAPI.Servers.Request'Class;
         Reply   : in out OpenAPI.Servers.Response'Class;
         Stream  : in out OpenAPI.Servers.Output_Stream'Class;
         Context : in out OpenAPI.Servers.Context_Type)
      is
         Impl    : Implementation_Type;
         Options : OpenAPI.Nullable_UString;
         Result  : TestAPI.Models.IntStruct_Type;
      begin

         OpenAPI.Servers.Get_Query_Parameter (Req, "options", Options);

         Impl.Test_Int (Options, Result, Context);
         if Context.Get_Status = 200 then
            Context.Set_Description ("OK");

            Stream.Start_Document;
            Serialize (Stream, "", Result);
            Stream.End_Document;
            return;
         end if;

      end Test_Int;

      package API_Test_Text_Response is new OpenAPI.Servers.Operation
        (Handler => Test_Text_Response,
         Method  => OpenAPI.Servers.GET,
         URI     => URI_Prefix & "/testTextResponse",
         Mimes   => Media_List_2'Access);

      --
      procedure Test_Text_Response
        (Req     : in out OpenAPI.Servers.Request'Class;
         Reply   : in out OpenAPI.Servers.Response'Class;
         Stream  : in out OpenAPI.Servers.Output_Stream'Class;
         Context : in out OpenAPI.Servers.Context_Type)
      is
         Impl    : Implementation_Type;
         Options : OpenAPI.Nullable_UString;
         Result  : OpenAPI.UString;
      begin

         OpenAPI.Servers.Get_Query_Parameter (Req, "options", Options);

         Impl.Test_Text_Response (Options, Result, Context);
         if Context.Get_Status = 200 then
            Context.Set_Description ("OK");
            Stream.Write (OpenAPI.To_String (Result));

            return;
         end if;

      end Test_Text_Response;

      package API_Do_Create_Ticket is new OpenAPI.Servers.Operation
        (Handler => Do_Create_Ticket,
         Method  => OpenAPI.Servers.POST,
         URI     => URI_Prefix & "/tickets",
         Mimes   => null);

      --  Create a ticket
      procedure Do_Create_Ticket
        (Req     : in out OpenAPI.Servers.Request'Class;
         Reply   : in out OpenAPI.Servers.Response'Class;
         Stream  : in out OpenAPI.Servers.Output_Stream'Class;
         Context : in out OpenAPI.Servers.Context_Type)
      is
         Impl        : Implementation_Type;
         Title       : OpenAPI.UString;
         Owner       : OpenAPI.Nullable_UString;
         Status      : OpenAPI.Nullable_UString;
         Description : OpenAPI.Nullable_UString;
      begin
         if not Context.Is_Authenticated then
            Context.Set_Error (401, "Not authenticated");
            return;
         end if;
         if not Context.Has_Permission (ACL_Write_Ticket.Permission) then
            Context.Set_Error (403, "Permission denied");
            return;
         end if;

         OpenAPI.Servers.Get_Parameter (Context, "owner", Owner);
         OpenAPI.Servers.Get_Parameter (Context, "status", Status);
         OpenAPI.Servers.Get_Parameter (Context, "title", Title);
         OpenAPI.Servers.Get_Parameter (Context, "description", Description);
         Impl.Do_Create_Ticket (Title, Owner, Status, Description, Context);

      end Do_Create_Ticket;

      package API_Do_Delete_Ticket is new OpenAPI.Servers.Operation
        (Handler => Do_Delete_Ticket,
         Method  => OpenAPI.Servers.DELETE,
         URI     => URI_Prefix & "/tickets/{tid}",
         Mimes   => null);

      --  Delete a ticket
      procedure Do_Delete_Ticket
        (Req     : in out OpenAPI.Servers.Request'Class;
         Reply   : in out OpenAPI.Servers.Response'Class;
         Stream  : in out OpenAPI.Servers.Output_Stream'Class;
         Context : in out OpenAPI.Servers.Context_Type)
      is
         Impl : Implementation_Type;
         Tid  : OpenAPI.Long;
      begin
         if not Context.Is_Authenticated then
            Context.Set_Error (401, "Not authenticated");
            return;
         end if;
         if not Context.Has_Permission (ACL_Write_Ticket.Permission) then
            Context.Set_Error (403, "Permission denied");
            return;
         end if;

         OpenAPI.Servers.Get_Path_Parameter (Req, 1, Tid);

         Impl.Do_Delete_Ticket (Tid, Context);

      end Do_Delete_Ticket;

      package API_Do_Head_Ticket is new OpenAPI.Servers.Operation
        (Handler => Do_Head_Ticket,
         Method  => OpenAPI.Servers.HEAD,
         URI     => URI_Prefix & "/tickets",
         Mimes   => null);

      --  List the tickets
      procedure Do_Head_Ticket
        (Req     : in out OpenAPI.Servers.Request'Class;
         Reply   : in out OpenAPI.Servers.Response'Class;
         Stream  : in out OpenAPI.Servers.Output_Stream'Class;
         Context : in out OpenAPI.Servers.Context_Type)
      is
         Impl : Implementation_Type;
      begin
         if not Context.Is_Authenticated then
            Context.Set_Error (401, "Not authenticated");
            return;
         end if;
         if not Context.Has_Permission (ACL_Read_Ticket.Permission) then
            Context.Set_Error (403, "Permission denied");
            return;
         end if;

         Impl.Do_Head_Ticket (Context);

      end Do_Head_Ticket;

      package API_Do_Patch_Ticket is new OpenAPI.Servers.Operation
        (Handler => Do_Patch_Ticket,
         Method  => OpenAPI.Servers.PATCH,
         URI     => URI_Prefix & "/tickets/{tid}",
         Mimes   => Media_List_1'Access);

      --  Patch a ticket
      procedure Do_Patch_Ticket
        (Req     : in out OpenAPI.Servers.Request'Class;
         Reply   : in out OpenAPI.Servers.Response'Class;
         Stream  : in out OpenAPI.Servers.Output_Stream'Class;
         Context : in out OpenAPI.Servers.Context_Type)
      is
         Impl        : Implementation_Type;
         Tid         : OpenAPI.Long;
         Owner       : OpenAPI.Nullable_UString;
         Status      : OpenAPI.Nullable_UString;
         Title       : OpenAPI.Nullable_UString;
         Description : OpenAPI.Nullable_UString;
         Result      : TestAPI.Models.Ticket_Type;
      begin
         if not Context.Is_Authenticated then
            Context.Set_Error (401, "Not authenticated");
            return;
         end if;
         if not Context.Has_Permission (ACL_Write_Ticket.Permission) then
            Context.Set_Error (403, "Permission denied");
            return;
         end if;

         OpenAPI.Servers.Get_Path_Parameter (Req, 1, Tid);

         OpenAPI.Servers.Get_Parameter (Context, "owner", Owner);
         OpenAPI.Servers.Get_Parameter (Context, "status", Status);
         OpenAPI.Servers.Get_Parameter (Context, "title", Title);
         OpenAPI.Servers.Get_Parameter (Context, "description", Description);
         Impl.Do_Patch_Ticket
           (Tid, Owner, Status, Title, Description, Result, Context);
         if Context.Get_Status = 200 then
            Context.Set_Description ("successful operation");

            Stream.Start_Document;
            Serialize (Stream, "", Result);
            Stream.End_Document;
            return;
         end if;
         if Context.Get_Status = 405 then
            Context.Set_Description ("Invalid input");
            return;
         end if;

      end Do_Patch_Ticket;

      package API_Do_Update_Ticket is new OpenAPI.Servers.Operation
        (Handler => Do_Update_Ticket,
         Method  => OpenAPI.Servers.PUT,
         URI     => URI_Prefix & "/tickets/{tid}",
         Mimes   => Media_List_1'Access);

      --  Update a ticket
      procedure Do_Update_Ticket
        (Req     : in out OpenAPI.Servers.Request'Class;
         Reply   : in out OpenAPI.Servers.Response'Class;
         Stream  : in out OpenAPI.Servers.Output_Stream'Class;
         Context : in out OpenAPI.Servers.Context_Type)
      is
         Impl        : Implementation_Type;
         Tid         : OpenAPI.Long;
         Owner       : OpenAPI.Nullable_UString;
         Status      : OpenAPI.Nullable_UString;
         Title       : OpenAPI.Nullable_UString;
         Description : OpenAPI.Nullable_UString;
         Result      : TestAPI.Models.Ticket_Type;
      begin
         if not Context.Is_Authenticated then
            Context.Set_Error (401, "Not authenticated");
            return;
         end if;
         if not Context.Has_Permission (ACL_Write_Ticket.Permission) then
            Context.Set_Error (403, "Permission denied");
            return;
         end if;

         OpenAPI.Servers.Get_Path_Parameter (Req, 1, Tid);

         OpenAPI.Servers.Get_Parameter (Context, "owner", Owner);
         OpenAPI.Servers.Get_Parameter (Context, "status", Status);
         OpenAPI.Servers.Get_Parameter (Context, "title", Title);
         OpenAPI.Servers.Get_Parameter (Context, "description", Description);
         Impl.Do_Update_Ticket
           (Tid, Owner, Status, Title, Description, Result, Context);
         if Context.Get_Status = 200 then
            Context.Set_Description ("successful operation");

            Stream.Start_Document;
            Serialize (Stream, "", Result);
            Stream.End_Document;
            return;
         end if;
         if Context.Get_Status = 405 then
            Context.Set_Description ("Invalid input");
            return;
         end if;

      end Do_Update_Ticket;

      package API_Do_Get_Ticket is new OpenAPI.Servers.Operation
        (Handler => Do_Get_Ticket,
         Method  => OpenAPI.Servers.GET,
         URI     => URI_Prefix & "/tickets/{tid}",
         Mimes   => Media_List_1'Access);

      --  Get a ticket
      procedure Do_Get_Ticket
        (Req     : in out OpenAPI.Servers.Request'Class;
         Reply   : in out OpenAPI.Servers.Response'Class;
         Stream  : in out OpenAPI.Servers.Output_Stream'Class;
         Context : in out OpenAPI.Servers.Context_Type)
      is
         Impl   : Implementation_Type;
         Tid    : OpenAPI.Long;
         Result : TestAPI.Models.Ticket_Type;
      begin
         if not Context.Is_Authenticated then
            Context.Set_Error (401, "Not authenticated");
            return;
         end if;
         if not Context.Has_Permission (ACL_Read_Ticket.Permission) then
            Context.Set_Error (403, "Permission denied");
            return;
         end if;

         OpenAPI.Servers.Get_Path_Parameter (Req, 1, Tid);

         Impl.Do_Get_Ticket (Tid, Result, Context);
         if Context.Get_Status = 200 then
            Context.Set_Description ("successful operation");

            Stream.Start_Document;
            Serialize (Stream, "", Result);
            Stream.End_Document;
            return;
         end if;
         if Context.Get_Status = 400 then
            Context.Set_Description ("Invalid ID supplied");
            return;
         end if;
         if Context.Get_Status = 404 then
            Context.Set_Description ("Ticket not found");
            return;
         end if;

      end Do_Get_Ticket;

      package API_Do_List_Tickets is new OpenAPI.Servers.Operation
        (Handler => Do_List_Tickets,
         Method  => OpenAPI.Servers.GET,
         URI     => URI_Prefix & "/tickets",
         Mimes   => Media_List_1'Access);

      --  List the tickets
      procedure Do_List_Tickets
        (Req     : in out OpenAPI.Servers.Request'Class;
         Reply   : in out OpenAPI.Servers.Response'Class;
         Stream  : in out OpenAPI.Servers.Output_Stream'Class;
         Context : in out OpenAPI.Servers.Context_Type)
      is
         Impl   : Implementation_Type;
         Status : OpenAPI.Nullable_UString;
         Owner  : OpenAPI.Nullable_UString;
         Result : TestAPI.Models.Ticket_Type_Vectors.Vector;
      begin
         if not Context.Is_Authenticated then
            Context.Set_Error (401, "Not authenticated");
            return;
         end if;
         if not Context.Has_Permission (ACL_Read_Ticket.Permission) then
            Context.Set_Error (403, "Permission denied");
            return;
         end if;

         OpenAPI.Servers.Get_Query_Parameter (Req, "status", Status);

         OpenAPI.Servers.Get_Query_Parameter (Req, "owner", Owner);

         Impl.Do_List_Tickets (Status, Owner, Result, Context);
         if Context.Get_Status = 200 then
            Context.Set_Description ("successful operation");

            Stream.Start_Document;
            Serialize (Stream, "", Result);
            Stream.End_Document;
            return;
         end if;
         if Context.Get_Status = 400 then
            Context.Set_Description ("Invalid status value");
            return;
         end if;

      end Do_List_Tickets;

      package API_Do_Options_Ticket is new OpenAPI.Servers.Operation
        (Handler => Do_Options_Ticket,
         Method  => OpenAPI.Servers.OPTIONS,
         URI     => URI_Prefix & "/tickets/{tid}",
         Mimes   => Media_List_1'Access);

      --  Get a ticket
      procedure Do_Options_Ticket
        (Req     : in out OpenAPI.Servers.Request'Class;
         Reply   : in out OpenAPI.Servers.Response'Class;
         Stream  : in out OpenAPI.Servers.Output_Stream'Class;
         Context : in out OpenAPI.Servers.Context_Type)
      is
         Impl   : Implementation_Type;
         Tid    : OpenAPI.Long;
         Result : TestAPI.Models.Ticket_Type;
      begin
         if not Context.Is_Authenticated then
            Context.Set_Error (401, "Not authenticated");
            return;
         end if;
         if not Context.Has_Permission (ACL_Read_Ticket.Permission) then
            Context.Set_Error (403, "Permission denied");
            return;
         end if;

         OpenAPI.Servers.Get_Path_Parameter (Req, 1, Tid);

         Impl.Do_Options_Ticket (Tid, Result, Context);
         if Context.Get_Status = 200 then
            Context.Set_Description ("successful operation");

            Stream.Start_Document;
            Serialize (Stream, "", Result);
            Stream.End_Document;
            return;
         end if;
         if Context.Get_Status = 400 then
            Context.Set_Description ("Invalid ID supplied");
            return;
         end if;
         if Context.Get_Status = 404 then
            Context.Set_Description ("Ticket not found");
            return;
         end if;

      end Do_Options_Ticket;

      procedure Register
        (Server : in out OpenAPI.Servers.Application_Type'Class)
      is
      begin
         OpenAPI.Servers.Register (Server, API_Orch_Store.Definition);
         OpenAPI.Servers.Register (Server, API_Test_Int.Definition);
         OpenAPI.Servers.Register (Server, API_Test_Text_Response.Definition);
         OpenAPI.Servers.Register (Server, API_Do_Create_Ticket.Definition);
         OpenAPI.Servers.Register (Server, API_Do_Delete_Ticket.Definition);
         OpenAPI.Servers.Register (Server, API_Do_Head_Ticket.Definition);
         OpenAPI.Servers.Register (Server, API_Do_Patch_Ticket.Definition);
         OpenAPI.Servers.Register (Server, API_Do_Update_Ticket.Definition);
         OpenAPI.Servers.Register (Server, API_Do_Get_Ticket.Definition);
         OpenAPI.Servers.Register (Server, API_Do_List_Tickets.Definition);
         OpenAPI.Servers.Register (Server, API_Do_Options_Ticket.Definition);
      end Register;

   end Skeleton;

   package body Shared_Instance is

      --
      procedure Orch_Store
        (Req     : in out OpenAPI.Servers.Request'Class;
         Reply   : in out OpenAPI.Servers.Response'Class;
         Stream  : in out OpenAPI.Servers.Output_Stream'Class;
         Context : in out OpenAPI.Servers.Context_Type)
      is
         Input              : OpenAPI.Value_Type;
         Orch_Store_Request : OrchStoreRequest_Type;
      begin

         OpenAPI.Servers.Read (Req, Media_List_1, Input);

         TestAPI.Models.Deserialize (Input, "", Orch_Store_Request);
         Server.Orch_Store (Orch_Store_Request, Context);

      end Orch_Store;

      package API_Orch_Store is new OpenAPI.Servers.Operation
        (Handler => Orch_Store,
         Method  => OpenAPI.Servers.POST,
         URI     => URI_Prefix & "/orchestration",
         Mimes   => null);

      --
      procedure Test_Int
        (Req     : in out OpenAPI.Servers.Request'Class;
         Reply   : in out OpenAPI.Servers.Response'Class;
         Stream  : in out OpenAPI.Servers.Output_Stream'Class;
         Context : in out OpenAPI.Servers.Context_Type)
      is
         Options : OpenAPI.Nullable_UString;
         Result  : TestAPI.Models.IntStruct_Type;
      begin

         OpenAPI.Servers.Get_Query_Parameter (Req, "options", Options);

         Server.Test_Int (Options, Result, Context);
         if Context.Get_Status = 200 then
            Context.Set_Description ("OK");

            Stream.Start_Document;
            Serialize (Stream, "", Result);
            Stream.End_Document;
            return;
         end if;

      end Test_Int;

      package API_Test_Int is new OpenAPI.Servers.Operation
        (Handler => Test_Int,
         Method  => OpenAPI.Servers.GET,
         URI     => URI_Prefix & "/testInt",
         Mimes   => Media_List_1'Access);

      --
      procedure Test_Text_Response
        (Req     : in out OpenAPI.Servers.Request'Class;
         Reply   : in out OpenAPI.Servers.Response'Class;
         Stream  : in out OpenAPI.Servers.Output_Stream'Class;
         Context : in out OpenAPI.Servers.Context_Type)
      is
         Options : OpenAPI.Nullable_UString;
         Result  : OpenAPI.UString;
      begin

         OpenAPI.Servers.Get_Query_Parameter (Req, "options", Options);

         Server.Test_Text_Response (Options, Result, Context);
         if Context.Get_Status = 200 then
            Context.Set_Description ("OK");
            Stream.Write (OpenAPI.To_String (Result));

            return;
         end if;

      end Test_Text_Response;

      package API_Test_Text_Response is new OpenAPI.Servers.Operation
        (Handler => Test_Text_Response,
         Method  => OpenAPI.Servers.GET,
         URI     => URI_Prefix & "/testTextResponse",
         Mimes   => Media_List_2'Access);

      --  Create a ticket
      procedure Do_Create_Ticket
        (Req     : in out OpenAPI.Servers.Request'Class;
         Reply   : in out OpenAPI.Servers.Response'Class;
         Stream  : in out OpenAPI.Servers.Output_Stream'Class;
         Context : in out OpenAPI.Servers.Context_Type)
      is
         Title       : OpenAPI.UString;
         Owner       : OpenAPI.Nullable_UString;
         Status      : OpenAPI.Nullable_UString;
         Description : OpenAPI.Nullable_UString;
      begin
         if not Context.Is_Authenticated then
            Context.Set_Error (401, "Not authenticated");
            return;
         end if;
         if not Context.Has_Permission (ACL_Write_Ticket.Permission) then
            Context.Set_Error (403, "Permission denied");
            return;
         end if;

         OpenAPI.Servers.Get_Parameter (Context, "owner", Owner);
         OpenAPI.Servers.Get_Parameter (Context, "status", Status);
         OpenAPI.Servers.Get_Parameter (Context, "title", Title);
         OpenAPI.Servers.Get_Parameter (Context, "description", Description);
         Server.Do_Create_Ticket (Title, Owner, Status, Description, Context);

      end Do_Create_Ticket;

      package API_Do_Create_Ticket is new OpenAPI.Servers.Operation
        (Handler => Do_Create_Ticket,
         Method  => OpenAPI.Servers.POST,
         URI     => URI_Prefix & "/tickets",
         Mimes   => null);

      --  Delete a ticket
      procedure Do_Delete_Ticket
        (Req     : in out OpenAPI.Servers.Request'Class;
         Reply   : in out OpenAPI.Servers.Response'Class;
         Stream  : in out OpenAPI.Servers.Output_Stream'Class;
         Context : in out OpenAPI.Servers.Context_Type)
      is
         Tid : OpenAPI.Long;
      begin
         if not Context.Is_Authenticated then
            Context.Set_Error (401, "Not authenticated");
            return;
         end if;
         if not Context.Has_Permission (ACL_Write_Ticket.Permission) then
            Context.Set_Error (403, "Permission denied");
            return;
         end if;

         OpenAPI.Servers.Get_Path_Parameter (Req, 1, Tid);

         Server.Do_Delete_Ticket (Tid, Context);

      end Do_Delete_Ticket;

      package API_Do_Delete_Ticket is new OpenAPI.Servers.Operation
        (Handler => Do_Delete_Ticket,
         Method  => OpenAPI.Servers.DELETE,
         URI     => URI_Prefix & "/tickets/{tid}",
         Mimes   => null);

      --  List the tickets
      procedure Do_Head_Ticket
        (Req     : in out OpenAPI.Servers.Request'Class;
         Reply   : in out OpenAPI.Servers.Response'Class;
         Stream  : in out OpenAPI.Servers.Output_Stream'Class;
         Context : in out OpenAPI.Servers.Context_Type)
      is
      begin
         if not Context.Is_Authenticated then
            Context.Set_Error (401, "Not authenticated");
            return;
         end if;
         if not Context.Has_Permission (ACL_Read_Ticket.Permission) then
            Context.Set_Error (403, "Permission denied");
            return;
         end if;

         Server.Do_Head_Ticket (Context);

      end Do_Head_Ticket;

      package API_Do_Head_Ticket is new OpenAPI.Servers.Operation
        (Handler => Do_Head_Ticket,
         Method  => OpenAPI.Servers.HEAD,
         URI     => URI_Prefix & "/tickets",
         Mimes   => null);

      --  Patch a ticket
      procedure Do_Patch_Ticket
        (Req     : in out OpenAPI.Servers.Request'Class;
         Reply   : in out OpenAPI.Servers.Response'Class;
         Stream  : in out OpenAPI.Servers.Output_Stream'Class;
         Context : in out OpenAPI.Servers.Context_Type)
      is
         Tid         : OpenAPI.Long;
         Owner       : OpenAPI.Nullable_UString;
         Status      : OpenAPI.Nullable_UString;
         Title       : OpenAPI.Nullable_UString;
         Description : OpenAPI.Nullable_UString;
         Result      : TestAPI.Models.Ticket_Type;
      begin
         if not Context.Is_Authenticated then
            Context.Set_Error (401, "Not authenticated");
            return;
         end if;
         if not Context.Has_Permission (ACL_Write_Ticket.Permission) then
            Context.Set_Error (403, "Permission denied");
            return;
         end if;

         OpenAPI.Servers.Get_Path_Parameter (Req, 1, Tid);

         OpenAPI.Servers.Get_Parameter (Context, "owner", Owner);
         OpenAPI.Servers.Get_Parameter (Context, "status", Status);
         OpenAPI.Servers.Get_Parameter (Context, "title", Title);
         OpenAPI.Servers.Get_Parameter (Context, "description", Description);
         Server.Do_Patch_Ticket
           (Tid, Owner, Status, Title, Description, Result, Context);
         if Context.Get_Status = 200 then
            Context.Set_Description ("successful operation");

            Stream.Start_Document;
            Serialize (Stream, "", Result);
            Stream.End_Document;
            return;
         end if;
         if Context.Get_Status = 405 then
            Context.Set_Description ("Invalid input");
            return;
         end if;

      end Do_Patch_Ticket;

      package API_Do_Patch_Ticket is new OpenAPI.Servers.Operation
        (Handler => Do_Patch_Ticket,
         Method  => OpenAPI.Servers.PATCH,
         URI     => URI_Prefix & "/tickets/{tid}",
         Mimes   => Media_List_1'Access);

      --  Update a ticket
      procedure Do_Update_Ticket
        (Req     : in out OpenAPI.Servers.Request'Class;
         Reply   : in out OpenAPI.Servers.Response'Class;
         Stream  : in out OpenAPI.Servers.Output_Stream'Class;
         Context : in out OpenAPI.Servers.Context_Type)
      is
         Tid         : OpenAPI.Long;
         Owner       : OpenAPI.Nullable_UString;
         Status      : OpenAPI.Nullable_UString;
         Title       : OpenAPI.Nullable_UString;
         Description : OpenAPI.Nullable_UString;
         Result      : TestAPI.Models.Ticket_Type;
      begin
         if not Context.Is_Authenticated then
            Context.Set_Error (401, "Not authenticated");
            return;
         end if;
         if not Context.Has_Permission (ACL_Write_Ticket.Permission) then
            Context.Set_Error (403, "Permission denied");
            return;
         end if;

         OpenAPI.Servers.Get_Path_Parameter (Req, 1, Tid);

         OpenAPI.Servers.Get_Parameter (Context, "owner", Owner);
         OpenAPI.Servers.Get_Parameter (Context, "status", Status);
         OpenAPI.Servers.Get_Parameter (Context, "title", Title);
         OpenAPI.Servers.Get_Parameter (Context, "description", Description);
         Server.Do_Update_Ticket
           (Tid, Owner, Status, Title, Description, Result, Context);
         if Context.Get_Status = 200 then
            Context.Set_Description ("successful operation");

            Stream.Start_Document;
            Serialize (Stream, "", Result);
            Stream.End_Document;
            return;
         end if;
         if Context.Get_Status = 405 then
            Context.Set_Description ("Invalid input");
            return;
         end if;

      end Do_Update_Ticket;

      package API_Do_Update_Ticket is new OpenAPI.Servers.Operation
        (Handler => Do_Update_Ticket,
         Method  => OpenAPI.Servers.PUT,
         URI     => URI_Prefix & "/tickets/{tid}",
         Mimes   => Media_List_1'Access);

      --  Get a ticket
      procedure Do_Get_Ticket
        (Req     : in out OpenAPI.Servers.Request'Class;
         Reply   : in out OpenAPI.Servers.Response'Class;
         Stream  : in out OpenAPI.Servers.Output_Stream'Class;
         Context : in out OpenAPI.Servers.Context_Type)
      is
         Tid    : OpenAPI.Long;
         Result : TestAPI.Models.Ticket_Type;
      begin
         if not Context.Is_Authenticated then
            Context.Set_Error (401, "Not authenticated");
            return;
         end if;
         if not Context.Has_Permission (ACL_Read_Ticket.Permission) then
            Context.Set_Error (403, "Permission denied");
            return;
         end if;

         OpenAPI.Servers.Get_Path_Parameter (Req, 1, Tid);

         Server.Do_Get_Ticket (Tid, Result, Context);
         if Context.Get_Status = 200 then
            Context.Set_Description ("successful operation");

            Stream.Start_Document;
            Serialize (Stream, "", Result);
            Stream.End_Document;
            return;
         end if;
         if Context.Get_Status = 400 then
            Context.Set_Description ("Invalid ID supplied");
            return;
         end if;
         if Context.Get_Status = 404 then
            Context.Set_Description ("Ticket not found");
            return;
         end if;

      end Do_Get_Ticket;

      package API_Do_Get_Ticket is new OpenAPI.Servers.Operation
        (Handler => Do_Get_Ticket,
         Method  => OpenAPI.Servers.GET,
         URI     => URI_Prefix & "/tickets/{tid}",
         Mimes   => Media_List_1'Access);

      --  List the tickets
      procedure Do_List_Tickets
        (Req     : in out OpenAPI.Servers.Request'Class;
         Reply   : in out OpenAPI.Servers.Response'Class;
         Stream  : in out OpenAPI.Servers.Output_Stream'Class;
         Context : in out OpenAPI.Servers.Context_Type)
      is
         Status : OpenAPI.Nullable_UString;
         Owner  : OpenAPI.Nullable_UString;
         Result : TestAPI.Models.Ticket_Type_Vectors.Vector;
      begin
         if not Context.Is_Authenticated then
            Context.Set_Error (401, "Not authenticated");
            return;
         end if;
         if not Context.Has_Permission (ACL_Read_Ticket.Permission) then
            Context.Set_Error (403, "Permission denied");
            return;
         end if;

         OpenAPI.Servers.Get_Query_Parameter (Req, "status", Status);

         OpenAPI.Servers.Get_Query_Parameter (Req, "owner", Owner);

         Server.Do_List_Tickets (Status, Owner, Result, Context);
         if Context.Get_Status = 200 then
            Context.Set_Description ("successful operation");

            Stream.Start_Document;
            Serialize (Stream, "", Result);
            Stream.End_Document;
            return;
         end if;
         if Context.Get_Status = 400 then
            Context.Set_Description ("Invalid status value");
            return;
         end if;

      end Do_List_Tickets;

      package API_Do_List_Tickets is new OpenAPI.Servers.Operation
        (Handler => Do_List_Tickets,
         Method  => OpenAPI.Servers.GET,
         URI     => URI_Prefix & "/tickets",
         Mimes   => Media_List_1'Access);

      --  Get a ticket
      procedure Do_Options_Ticket
        (Req     : in out OpenAPI.Servers.Request'Class;
         Reply   : in out OpenAPI.Servers.Response'Class;
         Stream  : in out OpenAPI.Servers.Output_Stream'Class;
         Context : in out OpenAPI.Servers.Context_Type)
      is
         Tid    : OpenAPI.Long;
         Result : TestAPI.Models.Ticket_Type;
      begin
         if not Context.Is_Authenticated then
            Context.Set_Error (401, "Not authenticated");
            return;
         end if;
         if not Context.Has_Permission (ACL_Read_Ticket.Permission) then
            Context.Set_Error (403, "Permission denied");
            return;
         end if;

         OpenAPI.Servers.Get_Path_Parameter (Req, 1, Tid);

         Server.Do_Options_Ticket (Tid, Result, Context);
         if Context.Get_Status = 200 then
            Context.Set_Description ("successful operation");

            Stream.Start_Document;
            Serialize (Stream, "", Result);
            Stream.End_Document;
            return;
         end if;
         if Context.Get_Status = 400 then
            Context.Set_Description ("Invalid ID supplied");
            return;
         end if;
         if Context.Get_Status = 404 then
            Context.Set_Description ("Ticket not found");
            return;
         end if;

      end Do_Options_Ticket;

      package API_Do_Options_Ticket is new OpenAPI.Servers.Operation
        (Handler => Do_Options_Ticket,
         Method  => OpenAPI.Servers.OPTIONS,
         URI     => URI_Prefix & "/tickets/{tid}",
         Mimes   => Media_List_1'Access);

      procedure Register
        (Server : in out OpenAPI.Servers.Application_Type'Class)
      is
      begin
         OpenAPI.Servers.Register (Server, API_Orch_Store.Definition);
         OpenAPI.Servers.Register (Server, API_Test_Int.Definition);
         OpenAPI.Servers.Register (Server, API_Test_Text_Response.Definition);
         OpenAPI.Servers.Register (Server, API_Do_Create_Ticket.Definition);
         OpenAPI.Servers.Register (Server, API_Do_Delete_Ticket.Definition);
         OpenAPI.Servers.Register (Server, API_Do_Head_Ticket.Definition);
         OpenAPI.Servers.Register (Server, API_Do_Patch_Ticket.Definition);
         OpenAPI.Servers.Register (Server, API_Do_Update_Ticket.Definition);
         OpenAPI.Servers.Register (Server, API_Do_Get_Ticket.Definition);
         OpenAPI.Servers.Register (Server, API_Do_List_Tickets.Definition);
         OpenAPI.Servers.Register (Server, API_Do_Options_Ticket.Definition);
      end Register;

      protected body Server is
         --
         procedure Orch_Store
           (Orch_Store_Request : in     OrchStoreRequest_Type;
            Context            : in out OpenAPI.Servers.Context_Type)
         is
         begin
            Impl.Orch_Store (Orch_Store_Request, Context);
         end Orch_Store;

         --
         procedure Test_Int
           (Options : in     OpenAPI.Nullable_UString;
            Result  :    out TestAPI.Models.IntStruct_Type;
            Context : in out OpenAPI.Servers.Context_Type)
         is
         begin
            Impl.Test_Int (Options, Result, Context);
         end Test_Int;

         --
         procedure Test_Text_Response
           (Options : in     OpenAPI.Nullable_UString;
            Result  :    out OpenAPI.UString;
            Context : in out OpenAPI.Servers.Context_Type)
         is
         begin
            Impl.Test_Text_Response (Options, Result, Context);
         end Test_Text_Response;

         --  Create a ticket
         procedure Do_Create_Ticket
           (Title       : in     OpenAPI.UString;
            Owner       : in     OpenAPI.Nullable_UString;
            Status      : in     OpenAPI.Nullable_UString;
            Description : in     OpenAPI.Nullable_UString;
            Context     : in out OpenAPI.Servers.Context_Type)
         is
         begin
            Impl.Do_Create_Ticket (Title, Owner, Status, Description, Context);
         end Do_Create_Ticket;

         --  Delete a ticket
         procedure Do_Delete_Ticket
           (Tid     : in     OpenAPI.Long;
            Context : in out OpenAPI.Servers.Context_Type)
         is
         begin
            Impl.Do_Delete_Ticket (Tid, Context);
         end Do_Delete_Ticket;

         --  List the tickets
         procedure Do_Head_Ticket
           (Context : in out OpenAPI.Servers.Context_Type)
         is
         begin
            Impl.Do_Head_Ticket (Context);
         end Do_Head_Ticket;

         --  Patch a ticket
         procedure Do_Patch_Ticket
           (Tid         : in     OpenAPI.Long;
            Owner       : in     OpenAPI.Nullable_UString;
            Status      : in     OpenAPI.Nullable_UString;
            Title       : in     OpenAPI.Nullable_UString;
            Description : in     OpenAPI.Nullable_UString;
            Result      :    out TestAPI.Models.Ticket_Type;
            Context     : in out OpenAPI.Servers.Context_Type)
         is
         begin
            Impl.Do_Patch_Ticket
              (Tid, Owner, Status, Title, Description, Result, Context);
         end Do_Patch_Ticket;

         --  Update a ticket
         procedure Do_Update_Ticket
           (Tid         : in     OpenAPI.Long;
            Owner       : in     OpenAPI.Nullable_UString;
            Status      : in     OpenAPI.Nullable_UString;
            Title       : in     OpenAPI.Nullable_UString;
            Description : in     OpenAPI.Nullable_UString;
            Result      :    out TestAPI.Models.Ticket_Type;
            Context     : in out OpenAPI.Servers.Context_Type)
         is
         begin
            Impl.Do_Update_Ticket
              (Tid, Owner, Status, Title, Description, Result, Context);
         end Do_Update_Ticket;

         --  Get a ticket
         procedure Do_Get_Ticket
           (Tid     : in     OpenAPI.Long;
            Result  :    out TestAPI.Models.Ticket_Type;
            Context : in out OpenAPI.Servers.Context_Type)
         is
         begin
            Impl.Do_Get_Ticket (Tid, Result, Context);
         end Do_Get_Ticket;

         --  List the tickets
         procedure Do_List_Tickets
           (Status  : in     OpenAPI.Nullable_UString;
            Owner   : in     OpenAPI.Nullable_UString;
            Result  :    out TestAPI.Models.Ticket_Type_Vectors.Vector;
            Context : in out OpenAPI.Servers.Context_Type)
         is
         begin
            Impl.Do_List_Tickets (Status, Owner, Result, Context);
         end Do_List_Tickets;

         --  Get a ticket
         procedure Do_Options_Ticket
           (Tid     : in     OpenAPI.Long;
            Result  :    out TestAPI.Models.Ticket_Type;
            Context : in out OpenAPI.Servers.Context_Type)
         is
         begin
            Impl.Do_Options_Ticket (Tid, Result, Context);
         end Do_Options_Ticket;

      end Server;

   end Shared_Instance;

end TestAPI.Skeletons;
