--  REST API Validation
--  API to validate
--
--  OpenAPI spec version: 1.0.0
--  Contact: Stephane.Carrez@gmail.com
--
--  NOTE: This package is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
--  https://github.com/swagger-api/swagger-codegen.git
--  Do not edit the class manually.
with Swagger.Streams;
with Ada.Containers.Vectors;
package TestAPI.Models is


   --  ------------------------------
   --  Information about a ticket
   --  ------------------------------
   type Ticket_Type is
     record
       Id : Swagger.Long;
       Title : Swagger.UString;
       Description : Swagger.UString;
       Owner : Swagger.Nullable_UString;
       Create_Date : Swagger.Datetime;
       End_Date : Swagger.Nullable_Date;
       Update_Date : Swagger.Nullable_Date;
       Status : Swagger.UString;
     end record;

   package Ticket_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => Ticket_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Ticket_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Ticket_Type_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Ticket_Type);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out Ticket_Type_Vectors.Vector);



end TestAPI.Models;
