--  REST API types validation
--  Types to validate
--
--  The version of the OpenAPI document: 1.0.0
--
--
--  NOTE: This package is auto generated by OpenAPI-Generator 7.11.0-2024-11-24.
--  https://openapi-generator.tech
--  Do not edit the class manually.

package body Types.Models is
   pragma Style_Checks ("-bmrIu");

   pragma Warnings (Off, "*use clause for package*");

   use OpenAPI.Streams;

   procedure Serialize
     (Into  : in out OpenAPI.Streams.Output_Stream'Class;
      Name  : in     String;
      Value : in     Types.Models.RackInfo_Type)
   is
   begin
      Into.Start_Entity (Name);
      Into.Write_Long_Entity ("Id", Value.Id);
      Into.Write_Entity ("Name", Value.Name);
      if not Value.X.Is_Null then
         Into.Write_Entity ("X", Value.X);
      end if;
      if not Value.Y.Is_Null then
         Into.Write_Entity ("Y", Value.Y);
      end if;
      Serialize (Into, "V", Value.V);
      Into.End_Entity (Name);
   end Serialize;

   procedure Serialize
     (Into  : in out OpenAPI.Streams.Output_Stream'Class;
      Name  : in     String;
      Value : in     RackInfo_Type_Vectors.Vector)
   is
   begin
      Into.Start_Array (Name);
      for Item of Value loop
         Serialize (Into, "", Item);
      end loop;
      Into.End_Array (Name);
   end Serialize;

   procedure Deserialize
     (From  : in     OpenAPI.Value_Type;
      Name  : in     String;
      Value :    out Types.Models.RackInfo_Type)
   is
      Object : OpenAPI.Value_Type;
   begin
      OpenAPI.Streams.Deserialize (From, Name, Object);
      OpenAPI.Streams.Deserialize (Object, "Id", Value.Id);
      OpenAPI.Streams.Deserialize (Object, "Name", Value.Name);
      OpenAPI.Streams.Deserialize (Object, "X", Value.X);
      OpenAPI.Streams.Deserialize (Object, "Y", Value.Y);
      OpenAPI.Streams.Deserialize (Object, "V", Value.V);
   end Deserialize;

   procedure Deserialize
     (From  : in     OpenAPI.Value_Type;
      Name  : in     String;
      Value : in out RackInfo_Type_Vectors.Vector)
   is
      List : OpenAPI.Value_Array_Type;
      Item : Types.Models.RackInfo_Type;
   begin
      Value.Clear;
      OpenAPI.Streams.Deserialize (From, Name, List);
      for Data of List loop
         Deserialize (Data, "", Item);
         Value.Append (Item);
      end loop;
   end Deserialize;

end Types.Models;
