--  REST API types validation
--  Types to validate
--
--  The version of the OpenAPI document: 1.0.0
--
--
--  NOTE: This package is auto generated by OpenAPI-Generator 7.11.0-2024-11-24.
--  https://openapi-generator.tech
--  Do not edit the class manually.

with OpenAPI.Streams;
with Ada.Containers.Vectors;
package Types.Models is
   pragma Style_Checks ("-bmrIu");

   type RackInfo_Type is record
      Id   : OpenAPI.Long;
      Name : OpenAPI.UString;
      X    : OpenAPI.Nullable_UString;
      Y    : OpenAPI.Nullable_UString;
      V    : OpenAPI.Number;
   end record;

   package RackInfo_Type_Vectors is new Ada.Containers.Vectors
     (Index_Type => Positive, Element_Type => Types.Models.RackInfo_Type);

   procedure Serialize
     (Into  : in out OpenAPI.Streams.Output_Stream'Class;
      Name  : in     String;
      Value : in     Types.Models.RackInfo_Type);
   procedure Serialize
     (Into  : in out OpenAPI.Streams.Output_Stream'Class;
      Name  : in     String;
      Value : in     RackInfo_Type_Vectors.Vector);
   procedure Deserialize
     (From  : in     OpenAPI.Value_Type;
      Name  : in     String;
      Value :    out Types.Models.RackInfo_Type);
   procedure Deserialize
     (From  : in     OpenAPI.Value_Type;
      Name  : in     String;
      Value : in out RackInfo_Type_Vectors.Vector);

end Types.Models;
